// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO4fncs3_1mVGBw6cv07Xnx9D2v6nKgq4',
    appId: '1:10184593103:web:c0b6238fb6e986398371ba',
    messagingSenderId: '10184593103',
    projectId: 'flutter-mirea',
    authDomain: 'flutter-mirea.firebaseapp.com',
    storageBucket: 'flutter-mirea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeyz5BsW8bXOur0cz7PPsJAlops7jf7S8',
    appId: '1:10184593103:android:a60443c3ae69fea38371ba',
    messagingSenderId: '10184593103',
    projectId: 'flutter-mirea',
    storageBucket: 'flutter-mirea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbhB1rn-9bdRcc45FffdIaoUcb1mzduOE',
    appId: '1:10184593103:ios:54122ccdbe3eeae88371ba',
    messagingSenderId: '10184593103',
    projectId: 'flutter-mirea',
    storageBucket: 'flutter-mirea.firebasestorage.app',
    iosBundleId: 'com.example.flutterItems',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbhB1rn-9bdRcc45FffdIaoUcb1mzduOE',
    appId: '1:10184593103:ios:54122ccdbe3eeae88371ba',
    messagingSenderId: '10184593103',
    projectId: 'flutter-mirea',
    storageBucket: 'flutter-mirea.firebasestorage.app',
    iosBundleId: 'com.example.flutterItems',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBO4fncs3_1mVGBw6cv07Xnx9D2v6nKgq4',
    appId: '1:10184593103:web:68a8a187265e20c58371ba',
    messagingSenderId: '10184593103',
    projectId: 'flutter-mirea',
    authDomain: 'flutter-mirea.firebaseapp.com',
    storageBucket: 'flutter-mirea.firebasestorage.app',
  );

}